#   Copyright 2020 The KNIX Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-predel-job"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "manager.name" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      labels:
        app: {{ include "manager.name" . | quote }}
    spec:
{{ if (.Values.manager.createServiceAccounts) }}
      serviceAccountName: "{{ template "manager.fullname" . }}"
{{ else }}
      serviceAccountName: "default"
{{ end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-postdelete
        image: "{{ .Values.imageRepo }}{{ .Values.manager.setup.imagePath }}:{{ .Values.manager.setup.imageTag }}"
        resources:
{{ toYaml .Values.manager.setup.resources | indent 10}}
        command:
        - python3
        - /opt/mfn/ManagementService/management_cleanup.py
        volumeMounts:
        - name: new-workflow-conf
          mountPath: /opt/mfn/conf
        resources:
{{ toYaml .Values.manager.setup.resources | indent 10}}
      restartPolicy: Never
      volumes:
      - name: new-workflow-conf
        configMap:
          name: {{ include "manager.fullname" .  }}-new-workflow-conf
